title: "UNICOSMOS project webpage"
description: "Showcasing research and events carried out for the MSCA UNICOSMOS project"
baseurl: "/unicosmos.github.io"
url: "https://vvitale.github.io"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

